mysql:
  address: root:123456@tcp(127.0.0.1:3306)/QQ?charset=utf8mb4&parseTime=True&loc=Local
auth:
  secret: 123456
redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleCoon: 30
